[package]
name = "upgrid-api"
publish = false
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
base64.workspace = true
compio.workspace = true
compio-tls.workspace = true
cyper-axum.workspace = true
futures-channel.workspace = true
futures-core.workspace = true
futures-util.workspace = true
ring.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
synchrony.workspace = true
rustls.workspace = true
tracing.workspace = true
upgrid-config.workspace = true
upgrid-notification.workspace = true
upgrid-raft.workspace = true
url.workspace = true
utoipa.workspace = true
utoipa-axum.workspace = true
uuid.workspace = true
