[package]
name = "upgrid-api"
publish = false
version.workspace = true
edition.workspace = true

[dependencies]
async-stream.workspace = true
axum.workspace = true
axum-server.workspace = true
base64.workspace = true
futures-core.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true
upgrid-config.workspace = true
upgrid-notification.workspace = true
upgrid-raft.workspace = true
url.workspace = true
utoipa.workspace = true
utoipa-axum.workspace = true
uuid.workspace = true
