[package]
name = "upgrid"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
compio.workspace = true
snafu.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
upgrid-api.workspace = true
upgrid-config.workspace = true
upgrid-notification.workspace = true
upgrid-monitor.workspace = true
upgrid-raft.workspace = true
uuid.workspace = true
