[package]
name = "upgrid-config"
publish = false
version.workspace = true
edition.workspace = true

[dependencies]
base64.workspace = true
clap.workspace = true
figment.workspace = true
postcard.workspace = true
ring.workspace = true
serde.workspace = true
url.workspace = true
uuid.workspace = true
