[package]
name = "upgrid-raft"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
compio.workspace = true
futures-channel.workspace = true
openraft.workspace = true
openraft-rt-compio.workspace = true
postcard.workspace = true
redb.workspace = true
refinery.workspace = true
regex.workspace = true
ring.workspace = true
rhai.workspace = true
rusqlite.workspace = true
sea-query.workspace = true
sea-query-rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_json_path.workspace = true
snafu.workspace = true
synchrony.workspace = true
tracing.workspace = true
upgrid-config.workspace = true
upgrid-rpc.workspace = true
upgrid-transport.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
criterion.workspace = true
tracing-subscriber.workspace = true

[[bench]]
name = "persistence"
harness = false
