use super::*;

#[derive(Serialize, Deserialize)]
struct ApplicationStateV20260819ConnectivityAlerts {
    targets: BTreeMap<TargetId, TargetState>,
    node_targets: BTreeMap<TargetId, NodeTargetState>,
    secrets: BTreeMap<SecretId, Secret>,
    notification_channels: BTreeMap<NotificationChannelId, NotificationChannel>,
    default_notification_channels: BTreeSet<NotificationChannelId>,
    default_notifications_disabled: BTreeSet<TargetId>,
    alerts: BTreeMap<AlertId, Alert>,
    alert_acknowledgements: BTreeMap<AlertId, u64>,
    availability_transitions: BTreeMap<EvaluationId, AvailabilityTransition>,
    history_retention_ms: u64,
    history_rollup_retention_ms: u64,
    history_rollups: BTreeMap<TargetId, BTreeMap<u64, EvaluationRollup>>,
    target_trash_retention_ms: u64,
    trashed_targets: BTreeMap<TargetId, TrashedTarget>,
    processed_operations: BTreeMap<Uuid, ProcessedOperation>,
    latest_operation_at_ms: u64,
    assignments: BTreeMap<EvaluationAssignmentKey, EvaluationAssignment>,
    evaluation_batches: BTreeMap<EvaluationId, EvaluationBatch>,
    target_locations: BTreeMap<TargetId, u16>,
    join_tokens: BTreeMap<JoinTokenHash, u64>,
    join_token_uses: BTreeMap<JoinTokenHash, u64>,
    node_names: BTreeMap<Uuid, String>,
    draining_nodes: BTreeSet<Uuid>,
    identities: BTreeMap<IdentityId, OperatorIdentity>,
    api_tokens: BTreeMap<ApiTokenId, ApiToken>,
    public_status_enabled: bool,
    node_reachability: BTreeMap<Uuid, NodeReachability>,
    connectivity_failures: BTreeSet<DirectedRoute>,
    connectivity_failure_counts: BTreeMap<DirectedRoute, u8>,
    connectivity_success_count: u8,
    join_token_reservations: BTreeMap<Uuid, JoinTokenReservation>,
}

impl From<ApplicationStateV20260819ConnectivityAlerts> for ApplicationState {
    fn from(state: ApplicationStateV20260819ConnectivityAlerts) -> Self {
        let ApplicationStateV20260819ConnectivityAlerts {
            targets,
            node_targets,
            secrets,
            notification_channels,
            default_notification_channels,
            default_notifications_disabled,
            alerts,
            alert_acknowledgements,
            availability_transitions,
            history_retention_ms,
            history_rollup_retention_ms,
            history_rollups,
            target_trash_retention_ms,
            trashed_targets,
            processed_operations,
            latest_operation_at_ms,
            assignments,
            evaluation_batches,
            target_locations,
            join_tokens,
            join_token_uses,
            node_names,
            draining_nodes,
            identities,
            api_tokens,
            public_status_enabled,
            node_reachability,
            connectivity_failures,
            connectivity_failure_counts,
            connectivity_success_count,
            join_token_reservations,
        } = state;
        Self {
            targets,
            node_targets,
            secrets,
            notification_channels,
            default_notification_channels,
            default_notifications_disabled,
            alerts,
            alert_acknowledgements,
            availability_transitions,
            history_retention_ms,
            history_rollup_retention_ms,
            history_rollups,
            target_trash_retention_ms,
            trashed_targets,
            processed_operations,
            latest_operation_at_ms,
            assignments,
            evaluation_batches,
            target_locations,
            join_tokens,
            join_token_uses,
            node_names,
            draining_nodes,
            identities,
            api_tokens,
            public_status_enabled,
            node_reachability,
            connectivity_failures,
            connectivity_failure_counts,
            connectivity_success_count,
            connectivity_degraded: None,
            join_token_reservations,
        }
    }
}

pub(crate) fn decode(payload: &[u8]) -> Result<ApplicationState, postcard::Error> {
    postcard::from_bytes::<ApplicationStateV20260819ConnectivityAlerts>(payload).map(Into::into)
}

#[cfg(test)]
impl From<ApplicationState> for ApplicationStateV20260819ConnectivityAlerts {
    fn from(state: ApplicationState) -> Self {
        let ApplicationState {
            targets,
            node_targets,
            secrets,
            notification_channels,
            default_notification_channels,
            default_notifications_disabled,
            alerts,
            alert_acknowledgements,
            availability_transitions,
            history_retention_ms,
            history_rollup_retention_ms,
            history_rollups,
            target_trash_retention_ms,
            trashed_targets,
            processed_operations,
            latest_operation_at_ms,
            assignments,
            evaluation_batches,
            target_locations,
            join_tokens,
            join_token_uses,
            node_names,
            draining_nodes,
            identities,
            api_tokens,
            public_status_enabled,
            node_reachability,
            connectivity_failures,
            connectivity_failure_counts,
            connectivity_success_count,
            connectivity_degraded: _,
            join_token_reservations,
        } = state;
        Self {
            targets,
            node_targets,
            secrets,
            notification_channels,
            default_notification_channels,
            default_notifications_disabled,
            alerts,
            alert_acknowledgements,
            availability_transitions,
            history_retention_ms,
            history_rollup_retention_ms,
            history_rollups,
            target_trash_retention_ms,
            trashed_targets,
            processed_operations,
            latest_operation_at_ms,
            assignments,
            evaluation_batches,
            target_locations,
            join_tokens,
            join_token_uses,
            node_names,
            draining_nodes,
            identities,
            api_tokens,
            public_status_enabled,
            node_reachability,
            connectivity_failures,
            connectivity_failure_counts,
            connectivity_success_count,
            join_token_reservations,
        }
    }
}

#[cfg(test)]
pub(crate) fn encode(state: ApplicationState) -> Result<Vec<u8>, postcard::Error> {
    postcard::to_extend(
        &ApplicationStateV20260819ConnectivityAlerts::from(state),
        Vec::new(),
    )
}
